"""create tables first version

Revision ID: 07da477c6628
Revises: 
Create Date: 2024-08-22 18:32:50.371554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '07da477c6628'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='myapp'
    )
    op.create_table('movie',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='myapp'
    )
    op.create_table('actormovie',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['myapp.actor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['myapp.movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id'),
    schema='myapp'
    )
    op.create_table('address',
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address_line_1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address_line_2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('post_code', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['myapp.actor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='myapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address', schema='myapp')
    op.drop_table('actormovie', schema='myapp')
    op.drop_table('movie', schema='myapp')
    op.drop_table('actor', schema='myapp')
    # ### end Alembic commands ###
