services:

  database:
    image: postgres:16.4
    container_name: database
    # volumes:
    #   - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  omnidb:
    platform: linux/amd64 # for apple processors
    image: omnidbteam/omnidb:3.0.3b
    container_name: omnidb
    depends_on:
      - database
    ports:
      - 8001:8000
    # volumes: 
    #   - ./volumes/omnidb_server:/home/omnidb/.omnidb/omnidb-server

    # docker exec -it omnidb python omnidb-server.py --createsuperuser=user pass

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - 6379:6379

  app:
    image: fastapi-base:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    environment:
      APP_DATABASE_URL: postgresql+asyncpg://postgres:postgres@database/postgres
      APP_REDIS_URL: redis://redis:6379/0
    depends_on:
      - database
      - redis
    # command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
