extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # tracing
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # metrics
  prometheus:  # expose metrics in prometheus format at otel collector
    endpoint: otel_collector:8889
    metric_expiration: 180m
    const_labels:
      env: fastapi-prod

  #logs
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

processors:
  batch:

service:
  extensions:
    - zpages

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
