name: CI Workflow

on: [ push ]

jobs:

  ci-workflow:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    env:
      DOCKER_CACHE: /tmp/.buildx-cache/
      DOCKER_CACHE_ARGS: --cache-from type=local,src=$(DOCKER_CACHE) --cache-to type=local,mode=max,dest=$(DOCKER_CACHE)
    strategy:
      matrix:
        os: [Ubuntu] # [Ubuntu, Windows, macOS]
        python-version: ["3.12"]

    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Set Poetry environment
        run: poetry env use ${{ matrix.python-version }}

      - name: Install Dependencies
        run: poetry install --all-extras

      - name: Code Quality Check
        run: poetry run mypy app

      - name: Test
        run: poetry run task test
        env:
          # The hostname used to communicate with the Redis service container
          API_REDIS_URL: redis://@redis:6379/0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: | 
          docker buildx build -t fastapi-base . 

      # TODO: scan for vulnerabilities in the docker image
